jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: checkout repo
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 10.11.0
    - continue-on-error: true
      name: Cache local Maven repository
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      name: Cache local Go modules
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-gomod-${{ hashFiles('**/go.mod') }}
        path: ~/go/pkg/mod
    - continue-on-error: true
      name: Execute license check, checkstyle, findbugs, sortpom
      run: 'mkdir -p ~/.m2

        ALLUXIO_DOCKER_NO_TTY=true \

        ALLUXIO_DOCKER_GIT_CLEAN=true \

        ALLUXIO_CHECKSTYLE=true \

        dev/github/run_docker.sh

        '
      timeout-minutes: 60
    - continue-on-error: true
      if: always()
      name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: artifact
        path: '**/target/artifacts/*

          **/target/logs/*

          log*

          '
        retention-days: 7
name: Checkstyle, Findbugs, Doc Check, SortPom, etc.
on:
  repository_dispatch:
    types: trigger-ga___checkstyle.yml
