jobs:
  build:
    if: '!contains(github.event.pull_request.title, ''DOCFIX'') && !contains(github.event.pull_request.title,
      ''SKIPCI'')'
    name: 'modules: '
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: checkout repo
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 10.11.0
    - continue-on-error: true
      name: Cache local Maven repository
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-maven-java11-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
    - continue-on-error: true
      name: Cache local Go modules
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-gomod-${{ hashFiles('**/go.mod') }}
        path: ~/go/pkg/mod
    - continue-on-error: true
      id: test0
      name: Run tests
      run: 'mkdir -p ~/.m2

        # Set fork count to 1 so that fault tolerant tests are run sequentially as
        these tests have high overhead, starting and stopping multiple Alluxio processes

        ALLUXIO_DOCKER_FORK_COUNT=1 \

        ALLUXIO_DOCKER_NO_TTY=true \

        ALLUXIO_DOCKER_GIT_CLEAN=true \

        ALLUXIO_DOCKER_MVN_PROJECT_LIST=dora/tests/integration \

        ALLUXIO_DOCKER_MVN_TESTS=${{ matrix.modules }} \

        dev/github/run_docker.sh

        '
      timeout-minutes: 60
    - continue-on-error: true
      if: always()
      name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: artifact
        path: '**/target/surefire-reports/*

          **/target/artifacts/*

          **/target/logs/*

          '
        retention-days: 7
    strategy:
      fail-fast: false
      matrix:
        modules:
        - alluxio.server.ft.**,!alluxio.server.ft.journal.raft.**,!alluxio.server.ft.journal.ufs.**
        - alluxio.server.ft.journal.raft.**,alluxio.server.ft.journal.ufs.**
name: Java 8 Fault Tolerant Integration Tests
on:
  repository_dispatch:
    types: trigger-ga___java8_integration_tests_ft.yml
